version: '2'
services:
    sonar:
        build: ./sonar
        ports:
            - "9000:9000"
            - "9092:9092"
    jenkins:
        build: ./jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        depends_on:
            - sonar